#!/usr/bin/env bash

# Only works for nautilus
# TODO -- Make system independent when necessary
if [[ -n $1 ]]
then
    if [[ $# -gt 1 ]]
    then
        echo "Ignoring excess args"
    fi
    nautilus $1 &
else
    nautilus . &
fi
